name: Daily Word Job

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  run-dailyword:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily word script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python src/app/api/daily_word/daily/dailyword.py
